name: "Continuous Integration"

on:
  pull_request:
    branches: [master]
  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: pip install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -r requirements.txt
    - name: flake8
      run: |
        flake8 haaska.py
        flake8 test.py
        python -m pytest test.py